"""
Binance Adapter — auto-generated by iEarn.Bot generator.py
Do NOT commit credentials. Set environment variables instead.
"""
from __future__ import annotations

import os
import sys
from typing import Any, Dict, List

import requests
from dotenv import load_dotenv

# Allow running as __main__ from repo root
_HERE = os.path.dirname(os.path.abspath(__file__))
_SRC  = os.path.dirname(_HERE)
if _SRC not in sys.path:
    sys.path.insert(0, _SRC)

from adapters.base import MarketAdapter, ReadOnlyError  # noqa: F401

load_dotenv()


class BinanceAdapter(MarketAdapter):
    """
    Binance market adapter (auto-generated skeleton).

    Endpoints:
        #   markets: GET /api/v3/exchangeInfo
        #   price: GET /api/v3/ticker/price
        #   positions: GET /api/v3/account
        #   place_order: POST /api/v3/order
        #   cancel_order: DELETE /api/v3/order
    """

    name = "binance"
    trading_enabled = False

    def __init__(self, trading_enabled: bool = False) -> None:
        self.trading_enabled = trading_enabled
        self.api_key    = os.getenv("BINANCE_API_KEY", "")
        self.api_secret = os.getenv("BINANCE_API_SECRET", "")
        self.base_url   = "https://api.binance.com"
        self.session    = requests.Session()
        self.session.headers.update({"Content-Type": "application/json"})

    # ── Markets ─────────────────────────────────────────────────────────────

    def get_markets(self, query: str = "") -> List[Dict[str, Any]]:
        # TODO: implement using GET /api/v3/exchangeInfo
        return []

    # ── Prices ───────────────────────────────────────────────────────────────

    def get_price(self, market_id: str) -> Dict[str, float]:
        # TODO: implement using GET /api/v3/ticker/price
        return {}

    # ── Portfolio ─────────────────────────────────────────────────────────────

    def get_positions(self) -> List[Dict[str, Any]]:
        # TODO: implement using GET /api/v3/account
        return []

    def get_balances(self) -> Dict[str, float]:
        # TODO: fetch from account endpoint
        return {"usdc": 0.0, "native": 0.0}

    # ── Trading ──────────────────────────────────────────────────────────────

    def _place_order(self, order: Dict[str, Any]) -> Dict[str, Any]:
        # TODO: implement using POST /api/v3/order
        return {}

    def _cancel_order(self, order_id: str) -> Dict[str, Any]:
        # TODO: implement using DELETE /api/v3/order
        return {}

    # ── Health ───────────────────────────────────────────────────────────────

    def smoke_test(self) -> bool:
        print(f"[Binance] Smoke test...")
        try:
            balances = self.get_balances()
            print(f"[Binance] Balances: {balances}")
            markets = self.get_markets()
            print(f"[Binance] Markets fetched: {len(markets)}")
            print(f"[Binance] Smoke test PASSED (skeleton — no live calls yet)")
            return True
        except Exception as exc:
            print(f"[Binance] Smoke test FAILED: {exc}")
            return False


if __name__ == "__main__":
    if len(sys.argv) > 1 and sys.argv[1] == "smoke":
        adapter = BinanceAdapter()
        adapter.smoke_test()
