"""
Kalshi Adapter — auto-generated by iEarn.Bot generator.py
Do NOT commit credentials. Set environment variables instead.
"""
from __future__ import annotations

import os
import sys
from typing import Any, Dict, List

import requests
from dotenv import load_dotenv

# Allow running as __main__ from repo root
_HERE = os.path.dirname(os.path.abspath(__file__))
_SRC  = os.path.dirname(_HERE)
if _SRC not in sys.path:
    sys.path.insert(0, _SRC)

from adapters.base import MarketAdapter, ReadOnlyError  # noqa: F401

load_dotenv()


class KalshiAdapter(MarketAdapter):
    """
    Kalshi market adapter (auto-generated skeleton).

    Endpoints:
        #   markets: GET /markets
        #   price: GET /markets/{ticker}
        #   positions: GET /portfolio/positions
        #   place_order: POST /portfolio/orders
        #   cancel_order: DELETE /portfolio/orders/{order_id}
    """

    name = "kalshi"
    trading_enabled = False

    def __init__(self, trading_enabled: bool = False) -> None:
        self.trading_enabled = trading_enabled
        self.api_key    = os.getenv("KALSHI_API_KEY", "")
        self.api_secret = os.getenv("KALSHI_API_SECRET", "")
        self.base_url   = "https://trading-api.kalshi.com/trade-api/v2"
        self.session    = requests.Session()
        self.session.headers.update({"Content-Type": "application/json"})

    # ── Markets ─────────────────────────────────────────────────────────────

    def get_markets(self, query: str = "") -> List[Dict[str, Any]]:
        # TODO: implement using GET /markets
        return []

    # ── Prices ───────────────────────────────────────────────────────────────

    def get_price(self, market_id: str) -> Dict[str, float]:
        # TODO: implement using GET /markets/{ticker}
        return {}

    # ── Portfolio ─────────────────────────────────────────────────────────────

    def get_positions(self) -> List[Dict[str, Any]]:
        # TODO: implement using GET /portfolio/positions
        return []

    def get_balances(self) -> Dict[str, float]:
        # TODO: fetch from account endpoint
        return {"usdc": 0.0, "native": 0.0}

    # ── Trading ──────────────────────────────────────────────────────────────

    def _place_order(self, order: Dict[str, Any]) -> Dict[str, Any]:
        # TODO: implement using POST /portfolio/orders
        return {}

    def _cancel_order(self, order_id: str) -> Dict[str, Any]:
        # TODO: implement using DELETE /portfolio/orders/{order_id}
        return {}

    # ── Health ───────────────────────────────────────────────────────────────

    def smoke_test(self) -> bool:
        print(f"[Kalshi] Smoke test...")
        try:
            balances = self.get_balances()
            print(f"[Kalshi] Balances: {balances}")
            markets = self.get_markets()
            print(f"[Kalshi] Markets fetched: {len(markets)}")
            print(f"[Kalshi] Smoke test PASSED (skeleton — no live calls yet)")
            return True
        except Exception as exc:
            print(f"[Kalshi] Smoke test FAILED: {exc}")
            return False


if __name__ == "__main__":
    if len(sys.argv) > 1 and sys.argv[1] == "smoke":
        adapter = KalshiAdapter()
        adapter.smoke_test()
